### ISSUE TITLE
Please upload the latest changes

### ISSUE THREAD

**Issue by justcla** [qalisander/SidePanelSwitcher#3]
I have forked the repo, but it is showing version 1.0.
I notice the version on Marketplace is 1.0.7

Can you please commit the latest changes to the repo so I can help make fixes?
Thanks

**Comment by qalisander** [comment]
Hey. Last digit of 1.0.7 is just a build version. Adjusting build pipeline I made many builds of the same git changes. There are latest changes on github repo.
